import { Fisioterapeuta, ControleDiario, PlantaoDadosPaciente, UTI } from "./types";

// ===== Fotos da equipe (assets locais; ver data/fotosEquipe.ts) =====
import {
  fotoDolores,
  fotoKatiuscia,
  fotoBruna,
  fotoFelipe,
  fotoHelen,
  fotoJoyce,
  fotoMarissa,
  fotoNeliton,
  fotoDenise,
  fotoSarah,
  fotoRavilla,
  fotoJoaoVitor,
  fotoFernanda,
  fotoElisangela,
} from "./data/fotosEquipe";

export { fotoDolores };

// ===== MOCK DATA =====

export const mockFisioterapeutas: Fisioterapeuta[] = [
  {
    id: "1",
    nome: "Katiuscia",
    coren: "CREFITO-9/00001-F",
    telefone: "+55 62 9390-3089",
    email: "katiuscia@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoKatiuscia,
    createdAt: "2025-01-10",
    equipe: "adulto",
  },
  {
    id: "2",
    nome: "Bruna Martins",
    coren: "CREFITO-9/00002-F",
    telefone: "+55 62 9290-5859",
    email: "bruna.martins@santacasa.com",
    turno: "Vespertino",
    status: "Ativo",
    foto: fotoBruna,
    createdAt: "2025-01-15",
    equipe: "adulto",
  },
  {
    id: "3",
    nome: "Felipe",
    coren: "CREFITO-9/00003-F",
    telefone: "+55 62 9433-9671",
    email: "felipe@santacasa.com",
    turno: "Noturno",
    status: "Ativo",
    foto: fotoFelipe,
    createdAt: "2025-02-01",
    equipe: "adulto",
  },
  {
    id: "4",
    nome: "Helen Araújo",
    coren: "CREFITO-9/00004-F",
    telefone: "+55 62 9120-7933",
    email: "helen.araujo@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoHelen,
    createdAt: "2025-02-10",
    equipe: "adulto",
  },
  {
    id: "5",
    nome: "Marissa Campos",
    coren: "CREFITO-9/00006-F",
    telefone: "+55 62 9317-0664",
    email: "marissa.campos@santacasa.com",
    turno: "Noturno",
    status: "Ativo",
    foto: fotoMarissa,
    createdAt: "2025-02-20",
    equipe: "adulto",
  },
  {
    id: "6",
    nome: "Neliton Junior",
    coren: "CREFITO-9/00007-F",
    telefone: "+55 62 9503-1452",
    email: "neliton.junior@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoNeliton,
    createdAt: "2025-03-01",
    equipe: "adulto",
  },
  {
    id: "7",
    nome: "Denise",
    coren: "CREFITO-9/00008-F",
    telefone: "+55 62 9150-8366",
    email: "denise@santacasa.com",
    turno: "Vespertino",
    status: "Ativo",
    foto: fotoDenise,
    createdAt: "2025-03-05",
    equipe: "adulto",
  },
  {
    id: "8",
    nome: "Sarah Bueno",
    coren: "CREFITO-9/00009-F",
    telefone: "+55 62 8145-4966",
    email: "sarah.bueno@santacasa.com",
    turno: "Noturno",
    status: "Ativo",
    foto: fotoSarah,
    createdAt: "2025-03-10",
    equipe: "adulto",
  },
  // ── Equipe Pediátrica ─────────────────────
  {
    id: "9",
    nome: "Ravilla",
    coren: "CREFITO-9/00010-F",
    telefone: "+55 62 9640-8437",
    email: "ravilla@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoRavilla,
    createdAt: "2025-03-15",
    equipe: "pediatrico",
  },
  {
    id: "10",
    nome: "João Vitor Leal",
    coren: "CREFITO-9/00011-F",
    telefone: "+55 63 9242-5875",
    email: "joao.vitor@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoJoaoVitor,
    createdAt: "2025-03-20",
    equipe: "pediatrico",
  },
  {
    id: "11",
    nome: "Fernanda Leite",
    coren: "CREFITO-9/00012-F",
    telefone: "+55 62 9138-5064",
    email: "fernanda.leite@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoFernanda,
    createdAt: "2025-03-25",
    equipe: "pediatrico",
  },
  {
    id: "12",
    nome: "Elisângela Povoa",
    coren: "CREFITO-9/00013-F",
    telefone: "+55 34 9922-6122",
    email: "elisangela.povoa@santacasa.com",
    turno: "Matutino",
    status: "Ativo",
    foto: fotoElisangela,
    createdAt: "2025-04-01",
    equipe: "pediatrico",
  },
];

const criarLeitosControleDiario = () =>
  Array.from({ length: 10 }, (_, i) => ({
    numero: i + 1,
    da: "",
    paciente: i < 7 ? `Paciente ${i + 1}` : "",
    patologia: i < 7 ? ["DPOC", "IAM", "AVC", "Pneumonia", "Sepse", "TCE", "IC"][i] : "",
    vm: i < 3,
    masc: i >= 3 && i < 5,
    tenda: false,
    cn: i >= 5 && i < 7,
    aa: false,
    m: true,
    v: i % 2 === 0,
    n: i % 3 === 0,
  }));

export const mockControleDiario: ControleDiario[] = [
  {
    id: "cd1",
    data: "2025-04-04",
    leitos: criarLeitosControleDiario(),
    plantonistas: {
      matutino: { nome: "Katiuscia", atendimentos: "8" },
      vespertino: { nome: "Bruna Martins", atendimentos: "7" },
      noturno: { nome: "Felipe", atendimentos: "6" },
    },
    transferencias: "2",
    obitos: "0",
    ocorrencias: [
      { leito: "3", hora: "08:30", ocorrido: "Paciente extubado com sucesso" },
      { leito: "7", hora: "14:15", ocorrido: "Queda de saturação, conduta ajustada" },
    ],
    createdAt: "2025-04-04T07:00:00",
  },
];

const criarLeitosDadosPaciente = () =>
  Array.from({ length: 10 }, (_, i) => ({
    numero: i + 1,
    pacienteNome: i < 7 ? `Paciente ${i + 1}` : "",
    satO2: i < 7 ? String(94 + (i % 4)) : "",
    fc: i < 7 ? String(70 + i * 3) : "",
    suporte: i < 3 ? "VM" : i < 5 ? "VNI" : i < 7 ? "O2 cateter" : "",
    parametros: i < 3 ? "FiO2 40%, PEEP 5" : "",
    sedacao: i < 2 ? "Midazolam 0.1mg/kg/h" : "",
    complacencia: i < 3 ? String(35 + i * 2) : "",
    hemoglobina: "",
    hematocrito: "",
    leucocitos: "",
    plaquetas: "",
    gasoPh: "",
    gasoPaco2: "",
    gasoPao2: "",
    gasoHco3: "",
    gasoBe: "",
    gasoSao2: "",
    exameHemogramaSpdata: "",
    exameGasometriaArterialSpdata: "",
    estadoGeral: i < 7 ? ["Estável", "Regular", "Grave", "Estável", "Regular", "Estável", "Grave"][i] : "",
    obs: "",
  }));

export const mockPlantaoDadosPaciente: PlantaoDadosPaciente[] = [
  {
    id: "pdp1",
    data: "2025-04-04",
    turno: "Matutino",
    fisioterapeutaId: "1",
    leitos: criarLeitosDadosPaciente(),
    createdAt: "2025-04-04T07:00:00",
  },
];

// ===== UTIs e Setores =====
export const mockUTIs: UTI[] = [
  {
    id: "uti-01",
    nome: "UTI Adulto 01",
    nomeAbrev: "UTI 01",
    totalLeitos: 10,
    ativa: true,
    localizacao: "Bloco A – 2º andar",
    equipe: "adulto",
    tipo: "uti",
    cor: "teal",
  },
  {
    id: "uti-02",
    nome: "UTI Adulto 02",
    nomeAbrev: "UTI 02",
    totalLeitos: 10,
    ativa: true,
    localizacao: "Bloco B – 2º andar",
    equipe: "adulto",
    tipo: "uti",
    cor: "teal",
  },
  {
    id: "uti-neo",
    nome: "UTI Neo Natal",
    nomeAbrev: "UTI Neo",
    totalLeitos: 12,
    ativa: true,
    localizacao: "Bloco C – 1º andar",
    equipe: "pediatrico",
    tipo: "uti",
    cor: "violet",
  },
  {
    id: "uti-ped",
    nome: "UTI Pediátrica",
    nomeAbrev: "UTI Pedi",
    totalLeitos: 8,
    ativa: true,
    localizacao: "Bloco C – 2º andar",
    equipe: "pediatrico",
    tipo: "uti",
    cor: "violet",
  },
  {
    id: "enfermaria",
    nome: "Enfermaria",
    nomeAbrev: "Enf.",
    totalLeitos: 20,
    ativa: true,
    localizacao: "Bloco D – 1º andar",
    equipe: "enfermaria",
    tipo: "enfermaria",
    cor: "amber",
  },
];